services:
  electronyat-shop:
    image: only1adwy/electronyat-shop:latest
    deploy:
      mode: replicated
      replicas: 2
      update_config:
        parallelism: 1
      restart_policy:
        condition: on-failure
    volumes:
      - images-data:/ElectronyatShop/wwwroot/Images/
    environment:
        - ASPNETCORE_ENVIRONMENT=Production
    networks:
        - electronyat-shop
        - shared
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

volumes:
    db-data:
        driver: local
        name: db-data
    images-data:
        driver: local
        name: images-data

networks:
    electronyat-shop:
        driver: bridge
        name: electronyat-shop
    shared:
        driver: bridge
        name: shared
        external: true