name: aspnet-linting
on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore
        working-directory: ElectronyatShop

      - name: Build
        run: dotnet build --no-restore --verbosity normal
        working-directory: ElectronyatShop

      - name: Test
        run: dotnet test --no-build --verbosity normal
        working-directory: ElectronyatShop